### ISSUE TITLE
Error saving resource 

### ISSUE THREAD

**Issue by briangormanly** [briangormanly/outfox#51]
Working off master branch https://github.com/briangormanly/outfox/commit/d9e272d2080877152b5d8525c599ade1ca996aa0

I created a user <- verified in my db
Created a group <- verified in my db
On the group page I tried to add a resource (view group -> add resource) resource type link
filled in the following:
Title: What is a System?
Description: Video
Link URL: https://youtu.be/6l1bhm1xtbY

and i see this error 
[1] ::1 - - [19/Nov/2020:19:30:31 +0000] "GET /api/groups/1 HTTP/1.1" 304 -
[1] ::1 - - [19/Nov/2020:19:31:22 +0000] "GET /api/groups/1 HTTP/1.1" 304 -
[1] ValidationError [SequelizeValidationError]: notNull Violation: Resource.creatorid cannot be null
[1]     at InstanceValidator._validate (/Users/brian/projects/outfox/server/node_modules/sequelize/lib/instance-validator.js:78:13)
[1]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[1]     at async InstanceValidator._validateAndRunHooks (/Users/brian/projects/outfox/server/node_modules/sequelize/lib/instance-validator.js:111:7)
[1]     at async InstanceValidator.validate (/Users/brian/projects/outfox/server/node_modules/sequelize/lib/instance-validator.js:93:12)
[1]     at async Resource.save (/Users/brian/projects/outfox/server/node_modules/sequelize/lib/model.js:3877:7)
[1]     at async Function.create (/Users/brian/projects/outfox/server/node_modules/sequelize/lib/model.js:2207:12) {
[1]   errors: [
[1]     ValidationErrorItem {
[1]       message: 'Resource.creatorid cannot be null',
[1]       type: 'notNull Violation',
[1]       path: 'creatorid',
[1]       value: null,
[1]       origin: 'CORE',
[1]       instance: [Resource],
[1]       validatorKey: 'is_null',
[1]       validatorName: null,
[1]       validatorArgs: []
[1]     }
[1]   ]
[1] }
[1] ::1 - - [19/Nov/2020:19:33:37 +0000] "POST /api/resources HTTP/1.1" 500 52

and there is no data in the database... UI just returns to empty group

**Comment by briangormanly** [comment]
Just as a note the same resource was able to be created outside of the group (by creating a new resource on the dashboard)
